// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/delta-lp/DeltaLP.tsx": () => import("../components/mockups/delta-lp/DeltaLP.tsx")
};
